### ISSUE TITLE
Trial not working? 

### ISSUE THREAD

**Issue by en-mira** [oodesign/mesh-gradients#1]
Hey! I want to try your mesh gradient plugin on sketch :) Unfortunately nothing seems to be happening when I run the plugin. When I click "continue trial" the box just disappears. Am I missing something here? 
 
<img width="1202" alt="Screen Shot 2021-05-07 at 5 09 44 PM" src="https://user-images.githubusercontent.com/33505318/117519076-15f00880-af57-11eb-815f-8d9ce3add940.png">

**Comment by oodesign** [comment]
Hi @en-mira ,

We recently published v1.1.2, which fixes an issue that could cause the behavior you describe.
May you please check your Mesh Gradients version is up-to-date, try again, and let us know how it worked for you?

Thanks!

**Comment by oodesign** [comment]
Hi @en-mira ,

Are you still experiencing this issue?

Thanks!
