### ISSUE TITLE
Can't find .sketchplugin file

### ISSUE THREAD

**Issue by moarpie** [oodesign/mesh-gradients#2]
I downloaded the trial zip file, but there is no .sketchplugin file in it.

**Comment by oodesign** [comment]
Hi @moarpie ,

You may find the latest release[ here](https://github.com/oodesign/mesh-gradients/releases/tag/v1.1.3).
The ZIP file contains the .sketchplugin file. 

If you can't find it, may any other application (antivirus, defender, or any other blocker) be preventing it to unzip properly? 

![image](https://user-images.githubusercontent.com/11992834/118998149-7f294000-b989-11eb-8f48-e844623da09f.png)
