### ISSUE TITLE
Plugin is unresponsive

### ISSUE THREAD

**Issue by flugeiden** [oodesign/mesh-gradients#3]
I've bought the license for the plugin. So far I've restarted the machine, restarted Sketch, reinstalled the plugin, but everytime I click the "Mesh gradient"-button in the plugin-menu nothing happens. 

I've tried clicking that button while having a shape selected and no shapes selected, but still no respons from the plugin.

Currently running Sketch 61.2

**Comment by oodesign** [comment]
Hi @flugeiden ,

We just released v1.1.6, that fixes an issue that could cause the plugin to crash on Sketch versions that do not support color variables (prior to v69).

Could you please try to update to this latest version (you may get an auto-update notification in Sketch top-right corner) and let us know how it worked for you?

Thanks!

**Comment by flugeiden** [comment]
It works! Thank you very much:)
