### ISSUE TITLE
Plugin has trouble launching

### ISSUE THREAD

**Issue by Charliebegood** [oodesign/mesh-gradients#4]
Hi,
I've been having issues with the plugin. It won't start or takes several minutes to do so. I'm running the latest version of Sketch and the plugin on a 2013 Mac Pro.
No clue as to what is causing this slowness, any help would be appreciated.
Thanks!

**Comment by oodesign** [comment]
Hi @Charliebegood ,

I'm sorry you're having a bad experience with Mesh gradients :(

May I ask you...

- Which MacOS version are you on?
- Have you always experienced this issue when launching Mesh gradients? Otherwise, could you identify when did it start happening?
- May there be any element (VPN, firewall, network issue... ) that could be preventing Mesh gradients to connect to license authentication services?

Thanks!

**Comment by Charliebegood** [comment]
Hi @oodesign 

Thanks for your swift reply!
• I'm running Mac OS Monterey 12.2.1.
• I've always experienced issues with the plugin
• I'm gonna look into networking issues and report back although I doubt I'll find anything since I don't use a VPN or specific firewall rules. 
• At first I thought it was my large Sketch files, but the same applies to a brand new document with just a rectangle.
• I'll try on my MacBook and see if I experience the same issues. Can I register the same license on another computer?

Thanks!

**Comment by oodesign** [comment]
Hi @Charliebegood ,

I'm afraid the Mesh gradients for Sketch license is per device (per Gumroad restrictions), and each device may need a different license. We'll soon move to a better licensing model, but currently we have this limitation.

But please [send us an email](mailto:support@oodesign.me), and we'll be happy to provide you a test license key that you can use to activate the plugin on another device.

**Comment by Charliebegood** [comment]
Hi @oodesign 

I've installed the Sketch Dev Plugin and this is the error I get in the console when launching the plugin. Unfortunately I'm not familiar with plugin dev in Sketch so I can't really tell what's going on. Hope this helps!

`Error: could not get the document: <MOMethod: 0x600054553620 : target=0x6000032943c0<MSRemoteAssetLibrary: 0x6000032943c0>, selector=status>
    at value (/Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js:1:142540)
    at /Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:159862
    at forEach[native code] (/)
    at /Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:159704
    at s (/Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:160169)
    at d (/Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:2021587)
    at s (/Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:2018458)
    at /Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:2017928
    at x (/Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:2018109)
    at __skpm_run (/Users/charlesaubert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/mesh-gradients.sketchplugin/Contents/Sketch/Main.js:1:2050080)`

Thanks
