### ISSUE TITLE
Plugin won't launch

### ISSUE THREAD

**Issue by rafaelconde** [oodesign/mesh-gradients#5]
Running the plugin doesn't seem to do any thing, is it just me? 😊

Sketch: `Version 92 (151719)`
macOS: `13.0 Beta (22A5331f)`

**Comment by oodesign** [comment]
Hi @rafaelconde ,

I'm afraid we can't reproduce the issue you describe with our testing set, but I'm afraid it doesn't include macOS Ventura (in Beta) setups. 

- Does the issue occur as well on Monterey / Big Sur / ... ?
- Does the plugin fail for any document (new ones, simple ones, and files including libraries)?

Thanks!

**Comment by rafaelconde** [comment]
So sorry for the delay here…

Seems like either the new version of macOS Ventura Beta, or Sketch has fixed the issue for me 🎉

Closing the issue, and apologies for the noise!

**Comment by oodesign** [comment]
Glad it's working fine again for you! 😊
