### ISSUE TITLE
The MeshGradients plugin doesn't work on macOS 13.0 Ventura

### ISSUE THREAD

**Issue by diniska** [oodesign/mesh-gradients#6]
The plugin used to work correctly in previous macOS versions. But it doesn't launch on macOS Ventura. Apple M1 Max chip.

**Comment by oodesign** [comment]
Hi @diniska ,

We're aware of some issues happening with MacOS Ventura, and the team is working actively on them.
I'll be happy to let you know when we're able to release a fix for it.

Thanks for reaching out!
